# Generated by Django 6.0.1 on 2026-02-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resume_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
