# Generated by Django 6.0.1 on 2026-02-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_resume_coverage_resume_gap_resume_matched_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='comparison_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
