from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor
from django.http import HttpResponse
from datetime import datetime


def new_page_if_needed(p, y):
    if y < 80:
        p.showPage()
        p.setFont("Helvetica", 11)
        return 750
    return y


def generate_report(
        score,
        matched,
        missing,
        suggestions,
        username,
        roles,
        coverage,
        gap,
        explanations=None
):

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="resume_report.pdf"'

    p = canvas.Canvas(response, pagesize=letter)

    # ===== TITLE =====
    p.setFont("Helvetica-Bold", 18)
    p.setFillColor(HexColor("#2c7be5"))
    p.drawString(170, 750, "AI Resume Analysis Report")

    p.setFillColor(HexColor("#000000"))
    p.setFont("Helvetica", 11)

    y = 700

    # ===== Candidate Info =====
    p.setFont("Helvetica-Bold", 13)
    p.drawString(80, y, "Candidate Details")
    y -= 25

    p.setFont("Helvetica", 11)
    p.drawString(100, y, f"Name: {username}")
    y -= 20

    p.drawString(100, y, f"Match Score: {score}%")
    y -= 20

    p.drawString(100, y, f"Skill Coverage: {coverage}%")
    y -= 20

    p.drawString(100, y, f"Skill Gap: {gap}%")
    y -= 20

    p.drawString(100, y, f"Generated On: {datetime.now().strftime('%d-%m-%Y %H:%M')}")
    y -= 40

    # ===== Roles =====
    p.setFont("Helvetica-Bold", 13)
    p.drawString(80, y, "Recommended Roles")
    y -= 25

    p.setFont("Helvetica", 11)

    if roles:
        for role in roles:
            y = new_page_if_needed(p, y)
            p.drawString(100, y, f"• {role}")
            y -= 18
    else:
        p.drawString(100, y, "No role recommendations available")
        y -= 18

    y -= 20

    # ===== Matched Skills =====
    p.setFont("Helvetica-Bold", 13)
    p.drawString(80, y, "Matched Skills")
    y -= 25

    p.setFont("Helvetica", 11)

    if matched:
        for skill in matched:
            y = new_page_if_needed(p, y)
            p.drawString(100, y, f"✓ {skill}")

            if explanations and skill in explanations:
                y -= 15
                p.setFont("Helvetica-Oblique", 10)
                p.drawString(120, y, f"{explanations[skill]}")
                p.setFont("Helvetica", 11)

            y -= 18
    else:
        p.drawString(100, y, "No matched skills found")
        y -= 18

    y -= 20

    # ===== Missing Skills =====
    p.setFont("Helvetica-Bold", 13)
    p.drawString(80, y, "Missing Skills")
    y -= 25

    p.setFont("Helvetica", 11)

    if missing:
        for skill in missing:
            y = new_page_if_needed(p, y)
            p.drawString(100, y, f"✗ {skill}")
            y -= 18
    else:
        p.drawString(100, y, "No missing skills")
        y -= 18

    y -= 20

    # ===== Suggestions =====
    p.setFont("Helvetica-Bold", 13)
    p.drawString(80, y, "Improvement Suggestions")
    y -= 25

    p.setFont("Helvetica", 11)

    if suggestions:
        for sug in suggestions:
            y = new_page_if_needed(p, y)
            p.drawString(100, y, f"• {sug}")
            y -= 18
    else:
        p.drawString(100, y, "No suggestions available")
        y -= 18

    # ===== Footer =====
    p.setFont("Helvetica-Oblique", 9)
    p.drawString(170, 40, "Generated by AI Resume Analyzer")

    p.save()
    return response
